### ISSUE TITLE
Has your research been public?

### ISSUE THREAD

**Issue by dudududu12138** [ShenLab-Genomics/SpliceTransformer#1]
Hello, I  want to know your research result? Has your research been public? If so ,can you send me a link? Thanks!

**Comment by SilverNebula** [comment]
Hello! Our research work is currently under revision. We will share the link after it is published.

**Comment by Tang-pro** [comment]
@SilverNebula 
"That's interesting work, I am interested in your work. Please could you offer the preprint if it is convenient. You can see my email on my homepage. 
Have a great day!

**Comment by SilverNebula** [comment]
Thank you for your interest. Unfortunately, we are not making the preprints available at this time. However, our manuscript will be publicly available in a few months! We will keep updating the progress in this repository.

**Comment by Tang-pro** [comment]
@SilverNebula 
I understand, thank you.

**Comment by SilverNebula** [comment]
Our paper has now been published in Nature Communications (https://www.nature.com/articles/s41467-024-53088-6). We appreciate your attention!

**Comment by Tang-pro** [comment]
Congratulations, I would love to read it and leran from it!
