### ISSUE TITLE
Share the training dataset & script

### ISSUE THREAD

**Issue by shiro-kur** [ShenLab-Genomics/SpliceTransformer#4]
Hello. Great work.
Could you share the training dataset & training scripts ?
I would like to know more details on SpTransformer's superiority.
Thank you in advance 

Ryo, Kyoto University

**Comment by SilverNebula** [comment]
Please check the following link:
https://drive.google.com/file/d/1d8n4vHDSbXqpPc_JFEswLomSUDBgHvno/view
The weights should be able to download directly. If you encounter any issues, please contact us.
